name: CI
on: [pull_request, push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-and-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build tables
        run: python analysis/metrics/build_tables.py
      - name: Install test deps
        run: pip install -r analysis/requirements.txt
      - name: Run tests
        run: pytest -q
      - name: Build figure
        run: python analysis/figures/make_chart.py
      - uses: WtfJoke/setup-tectonic@v3
      - name: Build report PDF
        working-directory: report/tex
        run: |
          mkdir -p ../build
          tectonic -X compile main.tex --outdir ../build
          test -f ../build/main.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: couchman-report-pdf
          path: report/build/main.pdf
          retention-days: 7
